stages:
  - go_build
  - push_testing

go_build:
  stage: go_build
  image: golang:1.8
  artifacts:
    expire_in: 1 week
    paths:
      - bin/
  script:
   - apt-get update && apt-get install -y --no-install-recommends git
   - mkdir bin
   - mkdir -p $GOPATH/src/pos-proxy
   - cp -r * $GOPATH/src/pos-proxy
   - cd $GOPATH/src/pos-proxy
   - go get
   - go install
   - cp -r $GOPATH/bin/* $CI_PROJECT_DIR/bin
  only:
  - master

push_testing:
  image: google/cloud-sdk
  stage: push_testing
  dependencies:
    - go_build
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone us-central1-a
  - gcloud config set project corded-guild-155314
  - ls -sh bin
  only:
  - master
