stages:
  - go_build

go_build:
  stage: go_build
  image: golang:1.8
  artifacts:
    paths:
      - /go/bin
  script:
   - apt-get update && apt-get install -y --no-install-recommends git
   - mkdir -p "$GOPATH/src/pos-proxy"
   - cp -r * "$GOPATH/src/pos-proxy"
   - mkdir -p /etc/cloudinn/
   - cp config/config.json /etc/cloudinn/pos_config.json
   - cd "$GOPATH/src/pos-proxy"
   - go get
   - go install
   - ls /go/bin
  only:
  - master
