stages:
  - go_build
  - testing

go_build:
  stage: go_build
  image: golang:1.8
  artifacts:
    paths:
      - /go/bin
  script:
   - apt-get update && apt-get install -y --no-install-recommends git
   - mkdir -p "$GOPATH/src/pos-proxy"
   - cp -r * "$GOPATH/src/pos-proxy"
   - cd "$GOPATH/src/pos-proxy"
   - go get
   - go install
  only:
  - master

push_testing:
  image: google/cloud-sdk
  stage: testing
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone us-central1-a
  - gcloud config set project corded-guild-155314
  - ls -sh /go/bin
  only:
  - master
