stages:
  - go_build
  - push_testing
  - push_staging
  - push_live

go_build:
  stage: go_build
  image: golang:1.8
  artifacts:
    expire_in: 1 week
    paths:
      - bin/
  script:
   - apt-get update && apt-get install -y --no-install-recommends git
   - mkdir bin
   - mkdir -p $GOPATH/src/pos-proxy
   - cp -r * $GOPATH/src/pos-proxy
   - cd $GOPATH/src/pos-proxy
   - echo $CI_JOB_ID
   - go get
   - go build -ldflags "-X pos-proxy/config.BuildNumber=${CI_JOB_ID} -X pos-proxy/config.Version=2.0.0"
   - cp -r $GOPATH/src/pos-proxy/pos-proxy $CI_PROJECT_DIR/bin
   - $GOPATH/src/pos-proxy/pos-proxy version 
  only:
  - master

push_testing:
  image: google/cloud-sdk
  stage: push_testing
  dependencies:
    - go_build
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project pos-proxy
  - gsutil cp -r bin/ gs://pos-proxy/test/
  - gsutil cp -r templates/ gs://pos-proxy/test/bin/
  only:
  - master

push_staging:
  image: google/cloud-sdk
  stage: push_staging
  dependencies:
    - go_build
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project pos-proxy
  - gsutil cp -r bin/ gs://pos-proxy/staging/
  - gsutil cp -r templates/ gs://pos-proxy/staging/bin/
  only:
  - master
  when: manual

push_live:
  image: google/cloud-sdk
  stage: push_live
  dependencies:
    - go_build
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project pos-proxy
  - gsutil cp -r bin/ gs://pos-proxy/manage/
  - gsutil cp -r templates/ gs://pos-proxy/manage/bin/
  only:
  - master
  when: manual
