stages:
  - build_test
  - push_test
  - push_staging
  - push_manage
  - push_fod

build_test:
  stage: build_test
  image: golang:1.9
  artifacts:
    expire_in: 1 week
    paths:
      - build/
  script:
   - apt-get update && apt-get install -y --no-install-recommends git
   - mkdir build
   - mkdir -p $GOPATH/src/pos-proxy
   - cp -r * $GOPATH/src/pos-proxy
   - cd $GOPATH/src/pos-proxy
   - echo $CI_PIPELINE_ID
   - go get
   - go build -ldflags "-X pos-proxy/config.BuildNumber=${CI_PIPELINE_ID} -X pos-proxy/config.Version=2.0.0"
   - cp $GOPATH/src/pos-proxy/pos-proxy $CI_PROJECT_DIR/build
   - cp $GOPATH/src/pos-proxy/update.sh $CI_PROJECT_DIR/build
   - cp -r templates $GOPATH/src/pos-proxy/pos-proxy $CI_PROJECT_DIR/build
  only:
  - master

push_test:
  image: google/cloud-sdk
  stage: push_test
  dependencies:
    - build_test
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project corded-guild-155314
  - gsutil cp -r build/* gs://pos-proxy/test/${CI_PIPELINE_ID}/
  - gsutil acl -r ch -u AllUsers:R gs://pos-proxy/test/${CI_PIPELINE_ID}/*
  only:
  - master

push_staging:
  image: google/cloud-sdk
  stage: push_staging
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project corded-guild-155314
  - gsutil cp -r gs://pos-proxy/test/${CI_PIPELINE_ID}/* gs://pos-proxy/staging/${CI_PIPELINE_ID}/
  - gsutil acl -r ch -u AllUsers:R gs://pos-proxy/staging/${CI_PIPELINE_ID}/*
  only:
  - master
  when: manual

push_manage:
  image: google/cloud-sdk
  stage: push_manage
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project corded-guild-155314
  - gsutil cp -r gs://pos-proxy/test/${CI_PIPELINE_ID}/* gs://pos-proxy/manage/${CI_PIPELINE_ID}/
  - gsutil acl -r ch -u AllUsers:R gs://pos-proxy/manage/${CI_PIPELINE_ID}/*
  only:
  - master
  when: manual

push_fod:
  image: google/cloud-sdk
  stage: push_fod
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project corded-guild-155314
  - gsutil cp -r gs://pos-proxy/test/${CI_PIPELINE_ID}/* gs://pos-proxy/fod/${CI_PIPELINE_ID}/
  - gsutil acl -r ch -u AllUsers:R gs://pos-proxy/fod/${CI_PIPELINE_ID}/*
  only:
  - master
  when: manual
