platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9

inputs:
  - name: repo
  - name: proxy_build_number
    path: build_number

outputs:
  - name: build

run:
  path: repo/ci/scripts/build_go.sh
